/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AlertVariant } from "./components/ds-alert/ds-alert";
import { AvatarSize, AvatarStatus } from "./components/ds-avatar/ds-avatar";
import { BadgeSize, BadgeVariant } from "./components/ds-badge/ds-badge";
import { ButtonSize, ButtonVariant } from "./components/ds-button/ds-button";
import { BarChartItem } from "./components/ds-chart-bar/ds-chart-bar";
import { DonutChartItem } from "./components/ds-chart-donut/ds-chart-donut";
import { LineChartSeries } from "./components/ds-chart-line/ds-chart-line";
import { DropdownPlacement } from "./components/ds-dropdown/ds-dropdown";
import { InputSize, InputType } from "./components/ds-input/ds-input";
import { ModalSize } from "./components/ds-modal/ds-modal";
import { ProgressSize, ProgressVariant } from "./components/ds-progress/ds-progress";
import { SelectOption, SelectSize } from "./components/ds-select/ds-select";
import { SkeletonVariant } from "./components/ds-skeleton/ds-skeleton";
import { SpinnerSize } from "./components/ds-spinner/ds-spinner";
import { StatTrend } from "./components/ds-stat-card/ds-stat-card";
import { StepItem } from "./components/ds-stepper/ds-stepper";
import { SortEvent, SortOrder, TableColumn } from "./components/ds-table/ds-table";
import { TagSize, TagVariant } from "./components/ds-tag/ds-tag";
import { TimelineItem } from "./components/ds-timeline/ds-timeline";
import { ToastVariant } from "./components/ds-toast/ds-toast";
import { ToastPosition } from "./components/ds-toast/ds-toast-container";
import { ToggleSize } from "./components/ds-toggle/ds-toggle";
import { TooltipPlacement } from "./components/ds-tooltip/ds-tooltip";
export { AlertVariant } from "./components/ds-alert/ds-alert";
export { AvatarSize, AvatarStatus } from "./components/ds-avatar/ds-avatar";
export { BadgeSize, BadgeVariant } from "./components/ds-badge/ds-badge";
export { ButtonSize, ButtonVariant } from "./components/ds-button/ds-button";
export { BarChartItem } from "./components/ds-chart-bar/ds-chart-bar";
export { DonutChartItem } from "./components/ds-chart-donut/ds-chart-donut";
export { LineChartSeries } from "./components/ds-chart-line/ds-chart-line";
export { DropdownPlacement } from "./components/ds-dropdown/ds-dropdown";
export { InputSize, InputType } from "./components/ds-input/ds-input";
export { ModalSize } from "./components/ds-modal/ds-modal";
export { ProgressSize, ProgressVariant } from "./components/ds-progress/ds-progress";
export { SelectOption, SelectSize } from "./components/ds-select/ds-select";
export { SkeletonVariant } from "./components/ds-skeleton/ds-skeleton";
export { SpinnerSize } from "./components/ds-spinner/ds-spinner";
export { StatTrend } from "./components/ds-stat-card/ds-stat-card";
export { StepItem } from "./components/ds-stepper/ds-stepper";
export { SortEvent, SortOrder, TableColumn } from "./components/ds-table/ds-table";
export { TagSize, TagVariant } from "./components/ds-tag/ds-tag";
export { TimelineItem } from "./components/ds-timeline/ds-timeline";
export { ToastVariant } from "./components/ds-toast/ds-toast";
export { ToastPosition } from "./components/ds-toast/ds-toast-container";
export { ToggleSize } from "./components/ds-toggle/ds-toggle";
export { TooltipPlacement } from "./components/ds-tooltip/ds-tooltip";
export namespace Components {
    interface DsAccordion {
        /**
          * @default false
         */
        "multiple": boolean;
    }
    interface DsAccordionItem {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default ''
         */
        "value": string;
    }
    interface DsAlert {
        /**
          * @default false
         */
        "dismissible": boolean;
        /**
          * @default 'info'
         */
        "variant": AlertVariant;
    }
    interface DsAvatar {
        /**
          * @default ''
         */
        "alt": string;
        "initials"?: string;
        /**
          * @default 'md'
         */
        "size": AvatarSize;
        "src"?: string;
        "status"?: AvatarStatus;
    }
    interface DsBadge {
        /**
          * @default false
         */
        "pill": boolean;
        /**
          * @default 'md'
         */
        "size": BadgeSize;
        /**
          * @default 'neutral'
         */
        "variant": BadgeVariant;
    }
    interface DsBreadcrumb {
    }
    interface DsBreadcrumbItem {
        /**
          * @default false
         */
        "current": boolean;
        "href"?: string;
    }
    interface DsButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "fullWidth": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default 'md'
         */
        "size": ButtonSize;
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant": ButtonVariant;
    }
    interface DsCard {
        /**
          * @default false
         */
        "interactive": boolean;
        /**
          * @default 'md'
         */
        "padding": 'none' | 'sm' | 'md' | 'lg';
        /**
          * @default 'elevated'
         */
        "variant": 'elevated' | 'outlined' | 'filled';
    }
    interface DsChartBar {
        /**
          * @default true
         */
        "animated": boolean;
        /**
          * @default []
         */
        "data": BarChartItem[];
        /**
          * @default 200
         */
        "height": number;
        /**
          * @default 'vertical'
         */
        "orientation": 'vertical' | 'horizontal';
        /**
          * @default true
         */
        "showLabels": boolean;
        /**
          * @default true
         */
        "showValues": boolean;
    }
    interface DsChartDonut {
        /**
          * @default true
         */
        "animated": boolean;
        /**
          * @default ''
         */
        "centerLabel": string;
        /**
          * @default ''
         */
        "centerValue": string;
        /**
          * @default []
         */
        "data": DonutChartItem[];
        /**
          * @default true
         */
        "showCenter": boolean;
        /**
          * @default 200
         */
        "size": number;
        /**
          * @default 28
         */
        "thickness": number;
    }
    interface DsChartLine {
        /**
          * @default true
         */
        "animated": boolean;
        /**
          * @default 200
         */
        "height": number;
        /**
          * @default []
         */
        "series": LineChartSeries[];
        /**
          * @default true
         */
        "showArea": boolean;
        /**
          * @default true
         */
        "showDots": boolean;
        /**
          * @default true
         */
        "showGrid": boolean;
    }
    interface DsCheckbox {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "indeterminate": boolean;
        "name"?: string;
        "value"?: string;
    }
    interface DsCheckboxGroup {
        "errorMessage"?: string;
        /**
          * @default false
         */
        "invalid": boolean;
        "label"?: string;
        /**
          * @default 'vertical'
         */
        "orientation": 'horizontal' | 'vertical';
    }
    interface DsDropdown {
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 'bottom-start'
         */
        "placement": DropdownPlacement;
    }
    interface DsDropdownItem {
        /**
          * @default false
         */
        "danger": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
    }
    interface DsInput {
        "autocomplete"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        "errorMessage"?: string;
        "helperText"?: string;
        /**
          * @default false
         */
        "invalid": boolean;
        "label"?: string;
        "maxlength"?: number;
        "name"?: string;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'md'
         */
        "size": InputSize;
        /**
          * @default 'text'
         */
        "type": InputType;
        /**
          * @default ''
         */
        "value": string;
    }
    interface DsModal {
        /**
          * @default true
         */
        "closeOnBackdrop": boolean;
        /**
          * @default true
         */
        "closeOnEscape": boolean;
        "dialogLabel"?: string;
        "dialogLabelledBy"?: string;
        "hide": () => Promise<void>;
        /**
          * @default 'md'
         */
        "modalSize": ModalSize;
        /**
          * @default false
         */
        "open": boolean;
        "show": () => Promise<void>;
    }
    interface DsPagination {
        /**
          * @default 1
         */
        "currentPage": number;
        /**
          * @default 10
         */
        "pageSize": number;
        /**
          * @default 1
         */
        "siblingCount": number;
        /**
          * @default 0
         */
        "total": number;
    }
    interface DsProgress {
        "label"?: string;
        /**
          * @default 100
         */
        "max": number;
        /**
          * @default false
         */
        "showValue": boolean;
        /**
          * @default 'md'
         */
        "size": ProgressSize;
        /**
          * @default 0
         */
        "value": number;
        /**
          * @default 'primary'
         */
        "variant": ProgressVariant;
    }
    interface DsRadio {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "name"?: string;
        "value"?: string;
    }
    interface DsRadioGroup {
        "errorMessage"?: string;
        /**
          * @default false
         */
        "invalid": boolean;
        "label"?: string;
        /**
          * @default 'vertical'
         */
        "orientation": 'horizontal' | 'vertical';
        "value"?: string;
    }
    interface DsSelect {
        /**
          * @default false
         */
        "disabled": boolean;
        "errorMessage"?: string;
        "helperText"?: string;
        /**
          * @default false
         */
        "invalid": boolean;
        "label"?: string;
        "name"?: string;
        /**
          * @default []
         */
        "options": SelectOption[];
        /**
          * @default 'Select an option'
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default false
         */
        "searchable": boolean;
        /**
          * @default 'md'
         */
        "size": SelectSize;
        "value"?: string;
    }
    interface DsSkeleton {
        /**
          * @default ''
         */
        "height": string;
        /**
          * @default 'text'
         */
        "variant": SkeletonVariant;
        /**
          * @default '100%'
         */
        "width": string;
    }
    interface DsSpinner {
        /**
          * @default 'Loading'
         */
        "label": string;
        /**
          * @default 'md'
         */
        "size": SpinnerSize;
    }
    interface DsStatCard {
        /**
          * @default ''
         */
        "change": string;
        /**
          * @default ''
         */
        "description": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default 'neutral'
         */
        "trend": StatTrend;
        /**
          * @default ''
         */
        "value": string;
    }
    interface DsStepper {
        /**
          * @default 0
         */
        "activeStep": number;
        /**
          * @default 'horizontal'
         */
        "orientation": 'horizontal' | 'vertical';
        /**
          * @default []
         */
        "steps": StepItem[];
    }
    interface DsTab {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ''
         */
        "value": string;
    }
    interface DsTabPanel {
        /**
          * @default ''
         */
        "value": string;
    }
    interface DsTable {
        /**
          * @default []
         */
        "columns": TableColumn[];
        /**
          * @default false
         */
        "compact": boolean;
        /**
          * @default []
         */
        "data": Record<string, unknown>[];
        /**
          * @default true
         */
        "hoverable": boolean;
        "sortBy"?: string;
        /**
          * @default 'none'
         */
        "sortOrder": SortOrder;
        /**
          * @default false
         */
        "striped": boolean;
    }
    interface DsTabs {
        /**
          * @default 'horizontal'
         */
        "orientation": 'horizontal' | 'vertical';
        /**
          * @default ''
         */
        "value": string;
    }
    interface DsTag {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "removable": boolean;
        /**
          * @default 'md'
         */
        "size": TagSize;
        /**
          * @default 'neutral'
         */
        "variant": TagVariant;
    }
    interface DsTimeline {
        /**
          * @default []
         */
        "items": TimelineItem[];
    }
    interface DsToast {
        /**
          * @default true
         */
        "dismissible": boolean;
        /**
          * @default 5000
         */
        "duration": number;
        /**
          * @default 'info'
         */
        "variant": ToastVariant;
    }
    interface DsToastContainer {
        /**
          * @default 'top-right'
         */
        "position": ToastPosition;
    }
    interface DsToggle {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "name"?: string;
        /**
          * @default 'md'
         */
        "size": ToggleSize;
        "value"?: string;
    }
    interface DsTooltip {
        /**
          * @default ''
         */
        "content": string;
        /**
          * @default 200
         */
        "delay": number;
        /**
          * @default 'top'
         */
        "placement": TooltipPlacement;
    }
}
export interface DsAccordionItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsAccordionItemElement;
}
export interface DsAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsAlertElement;
}
export interface DsButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsButtonElement;
}
export interface DsCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsCheckboxElement;
}
export interface DsCheckboxGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsCheckboxGroupElement;
}
export interface DsDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsDropdownElement;
}
export interface DsDropdownItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsDropdownItemElement;
}
export interface DsInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsInputElement;
}
export interface DsModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsModalElement;
}
export interface DsPaginationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsPaginationElement;
}
export interface DsRadioCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsRadioElement;
}
export interface DsRadioGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsRadioGroupElement;
}
export interface DsSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsSelectElement;
}
export interface DsTableCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsTableElement;
}
export interface DsTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsTabsElement;
}
export interface DsTagCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsTagElement;
}
export interface DsToastCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsToastElement;
}
export interface DsToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDsToggleElement;
}
declare global {
    interface HTMLDsAccordionElement extends Components.DsAccordion, HTMLStencilElement {
    }
    var HTMLDsAccordionElement: {
        prototype: HTMLDsAccordionElement;
        new (): HTMLDsAccordionElement;
    };
    interface HTMLDsAccordionItemElementEventMap {
        "dsToggle": { value: string; open: boolean };
    }
    interface HTMLDsAccordionItemElement extends Components.DsAccordionItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsAccordionItemElementEventMap>(type: K, listener: (this: HTMLDsAccordionItemElement, ev: DsAccordionItemCustomEvent<HTMLDsAccordionItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsAccordionItemElementEventMap>(type: K, listener: (this: HTMLDsAccordionItemElement, ev: DsAccordionItemCustomEvent<HTMLDsAccordionItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsAccordionItemElement: {
        prototype: HTMLDsAccordionItemElement;
        new (): HTMLDsAccordionItemElement;
    };
    interface HTMLDsAlertElementEventMap {
        "dsDismiss": void;
    }
    interface HTMLDsAlertElement extends Components.DsAlert, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsAlertElementEventMap>(type: K, listener: (this: HTMLDsAlertElement, ev: DsAlertCustomEvent<HTMLDsAlertElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsAlertElementEventMap>(type: K, listener: (this: HTMLDsAlertElement, ev: DsAlertCustomEvent<HTMLDsAlertElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsAlertElement: {
        prototype: HTMLDsAlertElement;
        new (): HTMLDsAlertElement;
    };
    interface HTMLDsAvatarElement extends Components.DsAvatar, HTMLStencilElement {
    }
    var HTMLDsAvatarElement: {
        prototype: HTMLDsAvatarElement;
        new (): HTMLDsAvatarElement;
    };
    interface HTMLDsBadgeElement extends Components.DsBadge, HTMLStencilElement {
    }
    var HTMLDsBadgeElement: {
        prototype: HTMLDsBadgeElement;
        new (): HTMLDsBadgeElement;
    };
    interface HTMLDsBreadcrumbElement extends Components.DsBreadcrumb, HTMLStencilElement {
    }
    var HTMLDsBreadcrumbElement: {
        prototype: HTMLDsBreadcrumbElement;
        new (): HTMLDsBreadcrumbElement;
    };
    interface HTMLDsBreadcrumbItemElement extends Components.DsBreadcrumbItem, HTMLStencilElement {
    }
    var HTMLDsBreadcrumbItemElement: {
        prototype: HTMLDsBreadcrumbItemElement;
        new (): HTMLDsBreadcrumbItemElement;
    };
    interface HTMLDsButtonElementEventMap {
        "dsClick": MouseEvent;
    }
    interface HTMLDsButtonElement extends Components.DsButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsButtonElementEventMap>(type: K, listener: (this: HTMLDsButtonElement, ev: DsButtonCustomEvent<HTMLDsButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsButtonElementEventMap>(type: K, listener: (this: HTMLDsButtonElement, ev: DsButtonCustomEvent<HTMLDsButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsButtonElement: {
        prototype: HTMLDsButtonElement;
        new (): HTMLDsButtonElement;
    };
    interface HTMLDsCardElement extends Components.DsCard, HTMLStencilElement {
    }
    var HTMLDsCardElement: {
        prototype: HTMLDsCardElement;
        new (): HTMLDsCardElement;
    };
    interface HTMLDsChartBarElement extends Components.DsChartBar, HTMLStencilElement {
    }
    var HTMLDsChartBarElement: {
        prototype: HTMLDsChartBarElement;
        new (): HTMLDsChartBarElement;
    };
    interface HTMLDsChartDonutElement extends Components.DsChartDonut, HTMLStencilElement {
    }
    var HTMLDsChartDonutElement: {
        prototype: HTMLDsChartDonutElement;
        new (): HTMLDsChartDonutElement;
    };
    interface HTMLDsChartLineElement extends Components.DsChartLine, HTMLStencilElement {
    }
    var HTMLDsChartLineElement: {
        prototype: HTMLDsChartLineElement;
        new (): HTMLDsChartLineElement;
    };
    interface HTMLDsCheckboxElementEventMap {
        "dsChange": boolean;
    }
    interface HTMLDsCheckboxElement extends Components.DsCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsCheckboxElementEventMap>(type: K, listener: (this: HTMLDsCheckboxElement, ev: DsCheckboxCustomEvent<HTMLDsCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsCheckboxElementEventMap>(type: K, listener: (this: HTMLDsCheckboxElement, ev: DsCheckboxCustomEvent<HTMLDsCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsCheckboxElement: {
        prototype: HTMLDsCheckboxElement;
        new (): HTMLDsCheckboxElement;
    };
    interface HTMLDsCheckboxGroupElementEventMap {
        "dsGroupChange": void;
    }
    interface HTMLDsCheckboxGroupElement extends Components.DsCheckboxGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsCheckboxGroupElementEventMap>(type: K, listener: (this: HTMLDsCheckboxGroupElement, ev: DsCheckboxGroupCustomEvent<HTMLDsCheckboxGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsCheckboxGroupElementEventMap>(type: K, listener: (this: HTMLDsCheckboxGroupElement, ev: DsCheckboxGroupCustomEvent<HTMLDsCheckboxGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsCheckboxGroupElement: {
        prototype: HTMLDsCheckboxGroupElement;
        new (): HTMLDsCheckboxGroupElement;
    };
    interface HTMLDsDropdownElementEventMap {
        "dsOpen": void;
        "dsClose": void;
    }
    interface HTMLDsDropdownElement extends Components.DsDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsDropdownElementEventMap>(type: K, listener: (this: HTMLDsDropdownElement, ev: DsDropdownCustomEvent<HTMLDsDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsDropdownElementEventMap>(type: K, listener: (this: HTMLDsDropdownElement, ev: DsDropdownCustomEvent<HTMLDsDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsDropdownElement: {
        prototype: HTMLDsDropdownElement;
        new (): HTMLDsDropdownElement;
    };
    interface HTMLDsDropdownItemElementEventMap {
        "dsSelect": void;
    }
    interface HTMLDsDropdownItemElement extends Components.DsDropdownItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsDropdownItemElementEventMap>(type: K, listener: (this: HTMLDsDropdownItemElement, ev: DsDropdownItemCustomEvent<HTMLDsDropdownItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsDropdownItemElementEventMap>(type: K, listener: (this: HTMLDsDropdownItemElement, ev: DsDropdownItemCustomEvent<HTMLDsDropdownItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsDropdownItemElement: {
        prototype: HTMLDsDropdownItemElement;
        new (): HTMLDsDropdownItemElement;
    };
    interface HTMLDsInputElementEventMap {
        "dsInput": string;
        "dsChange": string;
        "dsFocus": void;
        "dsBlur": void;
    }
    interface HTMLDsInputElement extends Components.DsInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsInputElementEventMap>(type: K, listener: (this: HTMLDsInputElement, ev: DsInputCustomEvent<HTMLDsInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsInputElementEventMap>(type: K, listener: (this: HTMLDsInputElement, ev: DsInputCustomEvent<HTMLDsInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsInputElement: {
        prototype: HTMLDsInputElement;
        new (): HTMLDsInputElement;
    };
    interface HTMLDsModalElementEventMap {
        "dsOpen": void;
        "dsClose": void;
        "dsAfterOpen": void;
        "dsAfterClose": void;
    }
    interface HTMLDsModalElement extends Components.DsModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsModalElementEventMap>(type: K, listener: (this: HTMLDsModalElement, ev: DsModalCustomEvent<HTMLDsModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsModalElementEventMap>(type: K, listener: (this: HTMLDsModalElement, ev: DsModalCustomEvent<HTMLDsModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsModalElement: {
        prototype: HTMLDsModalElement;
        new (): HTMLDsModalElement;
    };
    interface HTMLDsPaginationElementEventMap {
        "dsPageChange": number;
    }
    interface HTMLDsPaginationElement extends Components.DsPagination, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsPaginationElementEventMap>(type: K, listener: (this: HTMLDsPaginationElement, ev: DsPaginationCustomEvent<HTMLDsPaginationElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsPaginationElementEventMap>(type: K, listener: (this: HTMLDsPaginationElement, ev: DsPaginationCustomEvent<HTMLDsPaginationElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsPaginationElement: {
        prototype: HTMLDsPaginationElement;
        new (): HTMLDsPaginationElement;
    };
    interface HTMLDsProgressElement extends Components.DsProgress, HTMLStencilElement {
    }
    var HTMLDsProgressElement: {
        prototype: HTMLDsProgressElement;
        new (): HTMLDsProgressElement;
    };
    interface HTMLDsRadioElementEventMap {
        "dsChange": string;
    }
    interface HTMLDsRadioElement extends Components.DsRadio, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsRadioElementEventMap>(type: K, listener: (this: HTMLDsRadioElement, ev: DsRadioCustomEvent<HTMLDsRadioElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsRadioElementEventMap>(type: K, listener: (this: HTMLDsRadioElement, ev: DsRadioCustomEvent<HTMLDsRadioElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsRadioElement: {
        prototype: HTMLDsRadioElement;
        new (): HTMLDsRadioElement;
    };
    interface HTMLDsRadioGroupElementEventMap {
        "dsChange": string;
    }
    interface HTMLDsRadioGroupElement extends Components.DsRadioGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsRadioGroupElementEventMap>(type: K, listener: (this: HTMLDsRadioGroupElement, ev: DsRadioGroupCustomEvent<HTMLDsRadioGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsRadioGroupElementEventMap>(type: K, listener: (this: HTMLDsRadioGroupElement, ev: DsRadioGroupCustomEvent<HTMLDsRadioGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsRadioGroupElement: {
        prototype: HTMLDsRadioGroupElement;
        new (): HTMLDsRadioGroupElement;
    };
    interface HTMLDsSelectElementEventMap {
        "dsChange": string;
        "dsSearch": string;
    }
    interface HTMLDsSelectElement extends Components.DsSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsSelectElementEventMap>(type: K, listener: (this: HTMLDsSelectElement, ev: DsSelectCustomEvent<HTMLDsSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsSelectElementEventMap>(type: K, listener: (this: HTMLDsSelectElement, ev: DsSelectCustomEvent<HTMLDsSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsSelectElement: {
        prototype: HTMLDsSelectElement;
        new (): HTMLDsSelectElement;
    };
    interface HTMLDsSkeletonElement extends Components.DsSkeleton, HTMLStencilElement {
    }
    var HTMLDsSkeletonElement: {
        prototype: HTMLDsSkeletonElement;
        new (): HTMLDsSkeletonElement;
    };
    interface HTMLDsSpinnerElement extends Components.DsSpinner, HTMLStencilElement {
    }
    var HTMLDsSpinnerElement: {
        prototype: HTMLDsSpinnerElement;
        new (): HTMLDsSpinnerElement;
    };
    interface HTMLDsStatCardElement extends Components.DsStatCard, HTMLStencilElement {
    }
    var HTMLDsStatCardElement: {
        prototype: HTMLDsStatCardElement;
        new (): HTMLDsStatCardElement;
    };
    interface HTMLDsStepperElement extends Components.DsStepper, HTMLStencilElement {
    }
    var HTMLDsStepperElement: {
        prototype: HTMLDsStepperElement;
        new (): HTMLDsStepperElement;
    };
    interface HTMLDsTabElement extends Components.DsTab, HTMLStencilElement {
    }
    var HTMLDsTabElement: {
        prototype: HTMLDsTabElement;
        new (): HTMLDsTabElement;
    };
    interface HTMLDsTabPanelElement extends Components.DsTabPanel, HTMLStencilElement {
    }
    var HTMLDsTabPanelElement: {
        prototype: HTMLDsTabPanelElement;
        new (): HTMLDsTabPanelElement;
    };
    interface HTMLDsTableElementEventMap {
        "dsSort": SortEvent;
        "dsRowClick": Record<string, unknown>;
    }
    interface HTMLDsTableElement extends Components.DsTable, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsTableElementEventMap>(type: K, listener: (this: HTMLDsTableElement, ev: DsTableCustomEvent<HTMLDsTableElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsTableElementEventMap>(type: K, listener: (this: HTMLDsTableElement, ev: DsTableCustomEvent<HTMLDsTableElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsTableElement: {
        prototype: HTMLDsTableElement;
        new (): HTMLDsTableElement;
    };
    interface HTMLDsTabsElementEventMap {
        "dsChange": string;
    }
    interface HTMLDsTabsElement extends Components.DsTabs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsTabsElementEventMap>(type: K, listener: (this: HTMLDsTabsElement, ev: DsTabsCustomEvent<HTMLDsTabsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsTabsElementEventMap>(type: K, listener: (this: HTMLDsTabsElement, ev: DsTabsCustomEvent<HTMLDsTabsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsTabsElement: {
        prototype: HTMLDsTabsElement;
        new (): HTMLDsTabsElement;
    };
    interface HTMLDsTagElementEventMap {
        "dsRemove": void;
    }
    interface HTMLDsTagElement extends Components.DsTag, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsTagElementEventMap>(type: K, listener: (this: HTMLDsTagElement, ev: DsTagCustomEvent<HTMLDsTagElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsTagElementEventMap>(type: K, listener: (this: HTMLDsTagElement, ev: DsTagCustomEvent<HTMLDsTagElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsTagElement: {
        prototype: HTMLDsTagElement;
        new (): HTMLDsTagElement;
    };
    interface HTMLDsTimelineElement extends Components.DsTimeline, HTMLStencilElement {
    }
    var HTMLDsTimelineElement: {
        prototype: HTMLDsTimelineElement;
        new (): HTMLDsTimelineElement;
    };
    interface HTMLDsToastElementEventMap {
        "dsDismiss": void;
    }
    interface HTMLDsToastElement extends Components.DsToast, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsToastElementEventMap>(type: K, listener: (this: HTMLDsToastElement, ev: DsToastCustomEvent<HTMLDsToastElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsToastElementEventMap>(type: K, listener: (this: HTMLDsToastElement, ev: DsToastCustomEvent<HTMLDsToastElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsToastElement: {
        prototype: HTMLDsToastElement;
        new (): HTMLDsToastElement;
    };
    interface HTMLDsToastContainerElement extends Components.DsToastContainer, HTMLStencilElement {
    }
    var HTMLDsToastContainerElement: {
        prototype: HTMLDsToastContainerElement;
        new (): HTMLDsToastContainerElement;
    };
    interface HTMLDsToggleElementEventMap {
        "dsChange": boolean;
    }
    interface HTMLDsToggleElement extends Components.DsToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLDsToggleElementEventMap>(type: K, listener: (this: HTMLDsToggleElement, ev: DsToggleCustomEvent<HTMLDsToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLDsToggleElementEventMap>(type: K, listener: (this: HTMLDsToggleElement, ev: DsToggleCustomEvent<HTMLDsToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLDsToggleElement: {
        prototype: HTMLDsToggleElement;
        new (): HTMLDsToggleElement;
    };
    interface HTMLDsTooltipElement extends Components.DsTooltip, HTMLStencilElement {
    }
    var HTMLDsTooltipElement: {
        prototype: HTMLDsTooltipElement;
        new (): HTMLDsTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "ds-accordion": HTMLDsAccordionElement;
        "ds-accordion-item": HTMLDsAccordionItemElement;
        "ds-alert": HTMLDsAlertElement;
        "ds-avatar": HTMLDsAvatarElement;
        "ds-badge": HTMLDsBadgeElement;
        "ds-breadcrumb": HTMLDsBreadcrumbElement;
        "ds-breadcrumb-item": HTMLDsBreadcrumbItemElement;
        "ds-button": HTMLDsButtonElement;
        "ds-card": HTMLDsCardElement;
        "ds-chart-bar": HTMLDsChartBarElement;
        "ds-chart-donut": HTMLDsChartDonutElement;
        "ds-chart-line": HTMLDsChartLineElement;
        "ds-checkbox": HTMLDsCheckboxElement;
        "ds-checkbox-group": HTMLDsCheckboxGroupElement;
        "ds-dropdown": HTMLDsDropdownElement;
        "ds-dropdown-item": HTMLDsDropdownItemElement;
        "ds-input": HTMLDsInputElement;
        "ds-modal": HTMLDsModalElement;
        "ds-pagination": HTMLDsPaginationElement;
        "ds-progress": HTMLDsProgressElement;
        "ds-radio": HTMLDsRadioElement;
        "ds-radio-group": HTMLDsRadioGroupElement;
        "ds-select": HTMLDsSelectElement;
        "ds-skeleton": HTMLDsSkeletonElement;
        "ds-spinner": HTMLDsSpinnerElement;
        "ds-stat-card": HTMLDsStatCardElement;
        "ds-stepper": HTMLDsStepperElement;
        "ds-tab": HTMLDsTabElement;
        "ds-tab-panel": HTMLDsTabPanelElement;
        "ds-table": HTMLDsTableElement;
        "ds-tabs": HTMLDsTabsElement;
        "ds-tag": HTMLDsTagElement;
        "ds-timeline": HTMLDsTimelineElement;
        "ds-toast": HTMLDsToastElement;
        "ds-toast-container": HTMLDsToastContainerElement;
        "ds-toggle": HTMLDsToggleElement;
        "ds-tooltip": HTMLDsTooltipElement;
    }
}
declare namespace LocalJSX {
    interface DsAccordion {
        /**
          * @default false
         */
        "multiple"?: boolean;
    }
    interface DsAccordionItem {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onDsToggle"?: (event: DsAccordionItemCustomEvent<{ value: string; open: boolean }>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface DsAlert {
        /**
          * @default false
         */
        "dismissible"?: boolean;
        "onDsDismiss"?: (event: DsAlertCustomEvent<void>) => void;
        /**
          * @default 'info'
         */
        "variant"?: AlertVariant;
    }
    interface DsAvatar {
        /**
          * @default ''
         */
        "alt"?: string;
        "initials"?: string;
        /**
          * @default 'md'
         */
        "size"?: AvatarSize;
        "src"?: string;
        "status"?: AvatarStatus;
    }
    interface DsBadge {
        /**
          * @default false
         */
        "pill"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: BadgeSize;
        /**
          * @default 'neutral'
         */
        "variant"?: BadgeVariant;
    }
    interface DsBreadcrumb {
    }
    interface DsBreadcrumbItem {
        /**
          * @default false
         */
        "current"?: boolean;
        "href"?: string;
    }
    interface DsButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        "onDsClick"?: (event: DsButtonCustomEvent<MouseEvent>) => void;
        /**
          * @default 'md'
         */
        "size"?: ButtonSize;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant"?: ButtonVariant;
    }
    interface DsCard {
        /**
          * @default false
         */
        "interactive"?: boolean;
        /**
          * @default 'md'
         */
        "padding"?: 'none' | 'sm' | 'md' | 'lg';
        /**
          * @default 'elevated'
         */
        "variant"?: 'elevated' | 'outlined' | 'filled';
    }
    interface DsChartBar {
        /**
          * @default true
         */
        "animated"?: boolean;
        /**
          * @default []
         */
        "data"?: BarChartItem[];
        /**
          * @default 200
         */
        "height"?: number;
        /**
          * @default 'vertical'
         */
        "orientation"?: 'vertical' | 'horizontal';
        /**
          * @default true
         */
        "showLabels"?: boolean;
        /**
          * @default true
         */
        "showValues"?: boolean;
    }
    interface DsChartDonut {
        /**
          * @default true
         */
        "animated"?: boolean;
        /**
          * @default ''
         */
        "centerLabel"?: string;
        /**
          * @default ''
         */
        "centerValue"?: string;
        /**
          * @default []
         */
        "data"?: DonutChartItem[];
        /**
          * @default true
         */
        "showCenter"?: boolean;
        /**
          * @default 200
         */
        "size"?: number;
        /**
          * @default 28
         */
        "thickness"?: number;
    }
    interface DsChartLine {
        /**
          * @default true
         */
        "animated"?: boolean;
        /**
          * @default 200
         */
        "height"?: number;
        /**
          * @default []
         */
        "series"?: LineChartSeries[];
        /**
          * @default true
         */
        "showArea"?: boolean;
        /**
          * @default true
         */
        "showDots"?: boolean;
        /**
          * @default true
         */
        "showGrid"?: boolean;
    }
    interface DsCheckbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "indeterminate"?: boolean;
        "name"?: string;
        "onDsChange"?: (event: DsCheckboxCustomEvent<boolean>) => void;
        "value"?: string;
    }
    interface DsCheckboxGroup {
        "errorMessage"?: string;
        /**
          * @default false
         */
        "invalid"?: boolean;
        "label"?: string;
        "onDsGroupChange"?: (event: DsCheckboxGroupCustomEvent<void>) => void;
        /**
          * @default 'vertical'
         */
        "orientation"?: 'horizontal' | 'vertical';
    }
    interface DsDropdown {
        "onDsClose"?: (event: DsDropdownCustomEvent<void>) => void;
        "onDsOpen"?: (event: DsDropdownCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 'bottom-start'
         */
        "placement"?: DropdownPlacement;
    }
    interface DsDropdownItem {
        /**
          * @default false
         */
        "danger"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onDsSelect"?: (event: DsDropdownItemCustomEvent<void>) => void;
    }
    interface DsInput {
        "autocomplete"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "errorMessage"?: string;
        "helperText"?: string;
        /**
          * @default false
         */
        "invalid"?: boolean;
        "label"?: string;
        "maxlength"?: number;
        "name"?: string;
        "onDsBlur"?: (event: DsInputCustomEvent<void>) => void;
        "onDsChange"?: (event: DsInputCustomEvent<string>) => void;
        "onDsFocus"?: (event: DsInputCustomEvent<void>) => void;
        "onDsInput"?: (event: DsInputCustomEvent<string>) => void;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: InputSize;
        /**
          * @default 'text'
         */
        "type"?: InputType;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface DsModal {
        /**
          * @default true
         */
        "closeOnBackdrop"?: boolean;
        /**
          * @default true
         */
        "closeOnEscape"?: boolean;
        "dialogLabel"?: string;
        "dialogLabelledBy"?: string;
        /**
          * @default 'md'
         */
        "modalSize"?: ModalSize;
        "onDsAfterClose"?: (event: DsModalCustomEvent<void>) => void;
        "onDsAfterOpen"?: (event: DsModalCustomEvent<void>) => void;
        "onDsClose"?: (event: DsModalCustomEvent<void>) => void;
        "onDsOpen"?: (event: DsModalCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface DsPagination {
        /**
          * @default 1
         */
        "currentPage"?: number;
        "onDsPageChange"?: (event: DsPaginationCustomEvent<number>) => void;
        /**
          * @default 10
         */
        "pageSize"?: number;
        /**
          * @default 1
         */
        "siblingCount"?: number;
        /**
          * @default 0
         */
        "total"?: number;
    }
    interface DsProgress {
        "label"?: string;
        /**
          * @default 100
         */
        "max"?: number;
        /**
          * @default false
         */
        "showValue"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: ProgressSize;
        /**
          * @default 0
         */
        "value"?: number;
        /**
          * @default 'primary'
         */
        "variant"?: ProgressVariant;
    }
    interface DsRadio {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "name"?: string;
        "onDsChange"?: (event: DsRadioCustomEvent<string>) => void;
        "value"?: string;
    }
    interface DsRadioGroup {
        "errorMessage"?: string;
        /**
          * @default false
         */
        "invalid"?: boolean;
        "label"?: string;
        "onDsChange"?: (event: DsRadioGroupCustomEvent<string>) => void;
        /**
          * @default 'vertical'
         */
        "orientation"?: 'horizontal' | 'vertical';
        "value"?: string;
    }
    interface DsSelect {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "errorMessage"?: string;
        "helperText"?: string;
        /**
          * @default false
         */
        "invalid"?: boolean;
        "label"?: string;
        "name"?: string;
        "onDsChange"?: (event: DsSelectCustomEvent<string>) => void;
        "onDsSearch"?: (event: DsSelectCustomEvent<string>) => void;
        /**
          * @default []
         */
        "options"?: SelectOption[];
        /**
          * @default 'Select an option'
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default false
         */
        "searchable"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: SelectSize;
        "value"?: string;
    }
    interface DsSkeleton {
        /**
          * @default ''
         */
        "height"?: string;
        /**
          * @default 'text'
         */
        "variant"?: SkeletonVariant;
        /**
          * @default '100%'
         */
        "width"?: string;
    }
    interface DsSpinner {
        /**
          * @default 'Loading'
         */
        "label"?: string;
        /**
          * @default 'md'
         */
        "size"?: SpinnerSize;
    }
    interface DsStatCard {
        /**
          * @default ''
         */
        "change"?: string;
        /**
          * @default ''
         */
        "description"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default 'neutral'
         */
        "trend"?: StatTrend;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface DsStepper {
        /**
          * @default 0
         */
        "activeStep"?: number;
        /**
          * @default 'horizontal'
         */
        "orientation"?: 'horizontal' | 'vertical';
        /**
          * @default []
         */
        "steps"?: StepItem[];
    }
    interface DsTab {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface DsTabPanel {
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface DsTable {
        /**
          * @default []
         */
        "columns"?: TableColumn[];
        /**
          * @default false
         */
        "compact"?: boolean;
        /**
          * @default []
         */
        "data"?: Record<string, unknown>[];
        /**
          * @default true
         */
        "hoverable"?: boolean;
        "onDsRowClick"?: (event: DsTableCustomEvent<Record<string, unknown>>) => void;
        "onDsSort"?: (event: DsTableCustomEvent<SortEvent>) => void;
        "sortBy"?: string;
        /**
          * @default 'none'
         */
        "sortOrder"?: SortOrder;
        /**
          * @default false
         */
        "striped"?: boolean;
    }
    interface DsTabs {
        "onDsChange"?: (event: DsTabsCustomEvent<string>) => void;
        /**
          * @default 'horizontal'
         */
        "orientation"?: 'horizontal' | 'vertical';
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface DsTag {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onDsRemove"?: (event: DsTagCustomEvent<void>) => void;
        /**
          * @default false
         */
        "removable"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: TagSize;
        /**
          * @default 'neutral'
         */
        "variant"?: TagVariant;
    }
    interface DsTimeline {
        /**
          * @default []
         */
        "items"?: TimelineItem[];
    }
    interface DsToast {
        /**
          * @default true
         */
        "dismissible"?: boolean;
        /**
          * @default 5000
         */
        "duration"?: number;
        "onDsDismiss"?: (event: DsToastCustomEvent<void>) => void;
        /**
          * @default 'info'
         */
        "variant"?: ToastVariant;
    }
    interface DsToastContainer {
        /**
          * @default 'top-right'
         */
        "position"?: ToastPosition;
    }
    interface DsToggle {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "name"?: string;
        "onDsChange"?: (event: DsToggleCustomEvent<boolean>) => void;
        /**
          * @default 'md'
         */
        "size"?: ToggleSize;
        "value"?: string;
    }
    interface DsTooltip {
        /**
          * @default ''
         */
        "content"?: string;
        /**
          * @default 200
         */
        "delay"?: number;
        /**
          * @default 'top'
         */
        "placement"?: TooltipPlacement;
    }

    interface DsAccordionAttributes {
        "multiple": boolean;
    }
    interface DsAccordionItemAttributes {
        "open": boolean;
        "disabled": boolean;
        "value": string;
    }
    interface DsAlertAttributes {
        "variant": AlertVariant;
        "dismissible": boolean;
    }
    interface DsAvatarAttributes {
        "src": string;
        "alt": string;
        "initials": string;
        "size": AvatarSize;
        "status": AvatarStatus;
    }
    interface DsBadgeAttributes {
        "variant": BadgeVariant;
        "size": BadgeSize;
        "pill": boolean;
    }
    interface DsBreadcrumbItemAttributes {
        "href": string;
        "current": boolean;
    }
    interface DsButtonAttributes {
        "variant": ButtonVariant;
        "size": ButtonSize;
        "disabled": boolean;
        "loading": boolean;
        "type": 'button' | 'submit' | 'reset';
        "fullWidth": boolean;
    }
    interface DsCardAttributes {
        "variant": 'elevated' | 'outlined' | 'filled';
        "interactive": boolean;
        "padding": 'none' | 'sm' | 'md' | 'lg';
    }
    interface DsChartBarAttributes {
        "height": number;
        "orientation": 'vertical' | 'horizontal';
        "showValues": boolean;
        "showLabels": boolean;
        "animated": boolean;
    }
    interface DsChartDonutAttributes {
        "size": number;
        "thickness": number;
        "showCenter": boolean;
        "centerLabel": string;
        "centerValue": string;
        "animated": boolean;
    }
    interface DsChartLineAttributes {
        "height": number;
        "showArea": boolean;
        "showDots": boolean;
        "showGrid": boolean;
        "animated": boolean;
    }
    interface DsCheckboxAttributes {
        "checked": boolean;
        "indeterminate": boolean;
        "disabled": boolean;
        "name": string;
        "value": string;
    }
    interface DsCheckboxGroupAttributes {
        "label": string;
        "orientation": 'horizontal' | 'vertical';
        "invalid": boolean;
        "errorMessage": string;
    }
    interface DsDropdownAttributes {
        "open": boolean;
        "placement": DropdownPlacement;
    }
    interface DsDropdownItemAttributes {
        "disabled": boolean;
        "danger": boolean;
    }
    interface DsInputAttributes {
        "type": InputType;
        "value": string;
        "placeholder": string;
        "size": InputSize;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
        "invalid": boolean;
        "label": string;
        "helperText": string;
        "errorMessage": string;
        "name": string;
        "autocomplete": string;
        "maxlength": number;
    }
    interface DsModalAttributes {
        "open": boolean;
        "modalSize": ModalSize;
        "closeOnBackdrop": boolean;
        "closeOnEscape": boolean;
        "dialogLabel": string;
        "dialogLabelledBy": string;
    }
    interface DsPaginationAttributes {
        "total": number;
        "pageSize": number;
        "currentPage": number;
        "siblingCount": number;
    }
    interface DsProgressAttributes {
        "value": number;
        "max": number;
        "variant": ProgressVariant;
        "size": ProgressSize;
        "label": string;
        "showValue": boolean;
    }
    interface DsRadioAttributes {
        "checked": boolean;
        "disabled": boolean;
        "name": string;
        "value": string;
    }
    interface DsRadioGroupAttributes {
        "label": string;
        "value": string;
        "orientation": 'horizontal' | 'vertical';
        "invalid": boolean;
        "errorMessage": string;
    }
    interface DsSelectAttributes {
        "value": string;
        "placeholder": string;
        "size": SelectSize;
        "disabled": boolean;
        "invalid": boolean;
        "searchable": boolean;
        "label": string;
        "helperText": string;
        "errorMessage": string;
        "required": boolean;
        "name": string;
    }
    interface DsSkeletonAttributes {
        "variant": SkeletonVariant;
        "width": string;
        "height": string;
    }
    interface DsSpinnerAttributes {
        "size": SpinnerSize;
        "label": string;
    }
    interface DsStatCardAttributes {
        "label": string;
        "value": string;
        "change": string;
        "trend": StatTrend;
        "description": string;
    }
    interface DsStepperAttributes {
        "activeStep": number;
        "orientation": 'horizontal' | 'vertical';
    }
    interface DsTabAttributes {
        "value": string;
        "disabled": boolean;
    }
    interface DsTabPanelAttributes {
        "value": string;
    }
    interface DsTableAttributes {
        "sortBy": string;
        "sortOrder": SortOrder;
        "striped": boolean;
        "hoverable": boolean;
        "compact": boolean;
    }
    interface DsTabsAttributes {
        "value": string;
        "orientation": 'horizontal' | 'vertical';
    }
    interface DsTagAttributes {
        "variant": TagVariant;
        "size": TagSize;
        "removable": boolean;
        "disabled": boolean;
    }
    interface DsToastAttributes {
        "variant": ToastVariant;
        "duration": number;
        "dismissible": boolean;
    }
    interface DsToastContainerAttributes {
        "position": ToastPosition;
    }
    interface DsToggleAttributes {
        "checked": boolean;
        "disabled": boolean;
        "size": ToggleSize;
        "name": string;
        "value": string;
    }
    interface DsTooltipAttributes {
        "content": string;
        "placement": TooltipPlacement;
        "delay": number;
    }

    interface IntrinsicElements {
        "ds-accordion": Omit<DsAccordion, keyof DsAccordionAttributes> & { [K in keyof DsAccordion & keyof DsAccordionAttributes]?: DsAccordion[K] } & { [K in keyof DsAccordion & keyof DsAccordionAttributes as `attr:${K}`]?: DsAccordionAttributes[K] } & { [K in keyof DsAccordion & keyof DsAccordionAttributes as `prop:${K}`]?: DsAccordion[K] };
        "ds-accordion-item": Omit<DsAccordionItem, keyof DsAccordionItemAttributes> & { [K in keyof DsAccordionItem & keyof DsAccordionItemAttributes]?: DsAccordionItem[K] } & { [K in keyof DsAccordionItem & keyof DsAccordionItemAttributes as `attr:${K}`]?: DsAccordionItemAttributes[K] } & { [K in keyof DsAccordionItem & keyof DsAccordionItemAttributes as `prop:${K}`]?: DsAccordionItem[K] };
        "ds-alert": Omit<DsAlert, keyof DsAlertAttributes> & { [K in keyof DsAlert & keyof DsAlertAttributes]?: DsAlert[K] } & { [K in keyof DsAlert & keyof DsAlertAttributes as `attr:${K}`]?: DsAlertAttributes[K] } & { [K in keyof DsAlert & keyof DsAlertAttributes as `prop:${K}`]?: DsAlert[K] };
        "ds-avatar": Omit<DsAvatar, keyof DsAvatarAttributes> & { [K in keyof DsAvatar & keyof DsAvatarAttributes]?: DsAvatar[K] } & { [K in keyof DsAvatar & keyof DsAvatarAttributes as `attr:${K}`]?: DsAvatarAttributes[K] } & { [K in keyof DsAvatar & keyof DsAvatarAttributes as `prop:${K}`]?: DsAvatar[K] };
        "ds-badge": Omit<DsBadge, keyof DsBadgeAttributes> & { [K in keyof DsBadge & keyof DsBadgeAttributes]?: DsBadge[K] } & { [K in keyof DsBadge & keyof DsBadgeAttributes as `attr:${K}`]?: DsBadgeAttributes[K] } & { [K in keyof DsBadge & keyof DsBadgeAttributes as `prop:${K}`]?: DsBadge[K] };
        "ds-breadcrumb": DsBreadcrumb;
        "ds-breadcrumb-item": Omit<DsBreadcrumbItem, keyof DsBreadcrumbItemAttributes> & { [K in keyof DsBreadcrumbItem & keyof DsBreadcrumbItemAttributes]?: DsBreadcrumbItem[K] } & { [K in keyof DsBreadcrumbItem & keyof DsBreadcrumbItemAttributes as `attr:${K}`]?: DsBreadcrumbItemAttributes[K] } & { [K in keyof DsBreadcrumbItem & keyof DsBreadcrumbItemAttributes as `prop:${K}`]?: DsBreadcrumbItem[K] };
        "ds-button": Omit<DsButton, keyof DsButtonAttributes> & { [K in keyof DsButton & keyof DsButtonAttributes]?: DsButton[K] } & { [K in keyof DsButton & keyof DsButtonAttributes as `attr:${K}`]?: DsButtonAttributes[K] } & { [K in keyof DsButton & keyof DsButtonAttributes as `prop:${K}`]?: DsButton[K] };
        "ds-card": Omit<DsCard, keyof DsCardAttributes> & { [K in keyof DsCard & keyof DsCardAttributes]?: DsCard[K] } & { [K in keyof DsCard & keyof DsCardAttributes as `attr:${K}`]?: DsCardAttributes[K] } & { [K in keyof DsCard & keyof DsCardAttributes as `prop:${K}`]?: DsCard[K] };
        "ds-chart-bar": Omit<DsChartBar, keyof DsChartBarAttributes> & { [K in keyof DsChartBar & keyof DsChartBarAttributes]?: DsChartBar[K] } & { [K in keyof DsChartBar & keyof DsChartBarAttributes as `attr:${K}`]?: DsChartBarAttributes[K] } & { [K in keyof DsChartBar & keyof DsChartBarAttributes as `prop:${K}`]?: DsChartBar[K] };
        "ds-chart-donut": Omit<DsChartDonut, keyof DsChartDonutAttributes> & { [K in keyof DsChartDonut & keyof DsChartDonutAttributes]?: DsChartDonut[K] } & { [K in keyof DsChartDonut & keyof DsChartDonutAttributes as `attr:${K}`]?: DsChartDonutAttributes[K] } & { [K in keyof DsChartDonut & keyof DsChartDonutAttributes as `prop:${K}`]?: DsChartDonut[K] };
        "ds-chart-line": Omit<DsChartLine, keyof DsChartLineAttributes> & { [K in keyof DsChartLine & keyof DsChartLineAttributes]?: DsChartLine[K] } & { [K in keyof DsChartLine & keyof DsChartLineAttributes as `attr:${K}`]?: DsChartLineAttributes[K] } & { [K in keyof DsChartLine & keyof DsChartLineAttributes as `prop:${K}`]?: DsChartLine[K] };
        "ds-checkbox": Omit<DsCheckbox, keyof DsCheckboxAttributes> & { [K in keyof DsCheckbox & keyof DsCheckboxAttributes]?: DsCheckbox[K] } & { [K in keyof DsCheckbox & keyof DsCheckboxAttributes as `attr:${K}`]?: DsCheckboxAttributes[K] } & { [K in keyof DsCheckbox & keyof DsCheckboxAttributes as `prop:${K}`]?: DsCheckbox[K] };
        "ds-checkbox-group": Omit<DsCheckboxGroup, keyof DsCheckboxGroupAttributes> & { [K in keyof DsCheckboxGroup & keyof DsCheckboxGroupAttributes]?: DsCheckboxGroup[K] } & { [K in keyof DsCheckboxGroup & keyof DsCheckboxGroupAttributes as `attr:${K}`]?: DsCheckboxGroupAttributes[K] } & { [K in keyof DsCheckboxGroup & keyof DsCheckboxGroupAttributes as `prop:${K}`]?: DsCheckboxGroup[K] };
        "ds-dropdown": Omit<DsDropdown, keyof DsDropdownAttributes> & { [K in keyof DsDropdown & keyof DsDropdownAttributes]?: DsDropdown[K] } & { [K in keyof DsDropdown & keyof DsDropdownAttributes as `attr:${K}`]?: DsDropdownAttributes[K] } & { [K in keyof DsDropdown & keyof DsDropdownAttributes as `prop:${K}`]?: DsDropdown[K] };
        "ds-dropdown-item": Omit<DsDropdownItem, keyof DsDropdownItemAttributes> & { [K in keyof DsDropdownItem & keyof DsDropdownItemAttributes]?: DsDropdownItem[K] } & { [K in keyof DsDropdownItem & keyof DsDropdownItemAttributes as `attr:${K}`]?: DsDropdownItemAttributes[K] } & { [K in keyof DsDropdownItem & keyof DsDropdownItemAttributes as `prop:${K}`]?: DsDropdownItem[K] };
        "ds-input": Omit<DsInput, keyof DsInputAttributes> & { [K in keyof DsInput & keyof DsInputAttributes]?: DsInput[K] } & { [K in keyof DsInput & keyof DsInputAttributes as `attr:${K}`]?: DsInputAttributes[K] } & { [K in keyof DsInput & keyof DsInputAttributes as `prop:${K}`]?: DsInput[K] };
        "ds-modal": Omit<DsModal, keyof DsModalAttributes> & { [K in keyof DsModal & keyof DsModalAttributes]?: DsModal[K] } & { [K in keyof DsModal & keyof DsModalAttributes as `attr:${K}`]?: DsModalAttributes[K] } & { [K in keyof DsModal & keyof DsModalAttributes as `prop:${K}`]?: DsModal[K] };
        "ds-pagination": Omit<DsPagination, keyof DsPaginationAttributes> & { [K in keyof DsPagination & keyof DsPaginationAttributes]?: DsPagination[K] } & { [K in keyof DsPagination & keyof DsPaginationAttributes as `attr:${K}`]?: DsPaginationAttributes[K] } & { [K in keyof DsPagination & keyof DsPaginationAttributes as `prop:${K}`]?: DsPagination[K] };
        "ds-progress": Omit<DsProgress, keyof DsProgressAttributes> & { [K in keyof DsProgress & keyof DsProgressAttributes]?: DsProgress[K] } & { [K in keyof DsProgress & keyof DsProgressAttributes as `attr:${K}`]?: DsProgressAttributes[K] } & { [K in keyof DsProgress & keyof DsProgressAttributes as `prop:${K}`]?: DsProgress[K] };
        "ds-radio": Omit<DsRadio, keyof DsRadioAttributes> & { [K in keyof DsRadio & keyof DsRadioAttributes]?: DsRadio[K] } & { [K in keyof DsRadio & keyof DsRadioAttributes as `attr:${K}`]?: DsRadioAttributes[K] } & { [K in keyof DsRadio & keyof DsRadioAttributes as `prop:${K}`]?: DsRadio[K] };
        "ds-radio-group": Omit<DsRadioGroup, keyof DsRadioGroupAttributes> & { [K in keyof DsRadioGroup & keyof DsRadioGroupAttributes]?: DsRadioGroup[K] } & { [K in keyof DsRadioGroup & keyof DsRadioGroupAttributes as `attr:${K}`]?: DsRadioGroupAttributes[K] } & { [K in keyof DsRadioGroup & keyof DsRadioGroupAttributes as `prop:${K}`]?: DsRadioGroup[K] };
        "ds-select": Omit<DsSelect, keyof DsSelectAttributes> & { [K in keyof DsSelect & keyof DsSelectAttributes]?: DsSelect[K] } & { [K in keyof DsSelect & keyof DsSelectAttributes as `attr:${K}`]?: DsSelectAttributes[K] } & { [K in keyof DsSelect & keyof DsSelectAttributes as `prop:${K}`]?: DsSelect[K] };
        "ds-skeleton": Omit<DsSkeleton, keyof DsSkeletonAttributes> & { [K in keyof DsSkeleton & keyof DsSkeletonAttributes]?: DsSkeleton[K] } & { [K in keyof DsSkeleton & keyof DsSkeletonAttributes as `attr:${K}`]?: DsSkeletonAttributes[K] } & { [K in keyof DsSkeleton & keyof DsSkeletonAttributes as `prop:${K}`]?: DsSkeleton[K] };
        "ds-spinner": Omit<DsSpinner, keyof DsSpinnerAttributes> & { [K in keyof DsSpinner & keyof DsSpinnerAttributes]?: DsSpinner[K] } & { [K in keyof DsSpinner & keyof DsSpinnerAttributes as `attr:${K}`]?: DsSpinnerAttributes[K] } & { [K in keyof DsSpinner & keyof DsSpinnerAttributes as `prop:${K}`]?: DsSpinner[K] };
        "ds-stat-card": Omit<DsStatCard, keyof DsStatCardAttributes> & { [K in keyof DsStatCard & keyof DsStatCardAttributes]?: DsStatCard[K] } & { [K in keyof DsStatCard & keyof DsStatCardAttributes as `attr:${K}`]?: DsStatCardAttributes[K] } & { [K in keyof DsStatCard & keyof DsStatCardAttributes as `prop:${K}`]?: DsStatCard[K] };
        "ds-stepper": Omit<DsStepper, keyof DsStepperAttributes> & { [K in keyof DsStepper & keyof DsStepperAttributes]?: DsStepper[K] } & { [K in keyof DsStepper & keyof DsStepperAttributes as `attr:${K}`]?: DsStepperAttributes[K] } & { [K in keyof DsStepper & keyof DsStepperAttributes as `prop:${K}`]?: DsStepper[K] };
        "ds-tab": Omit<DsTab, keyof DsTabAttributes> & { [K in keyof DsTab & keyof DsTabAttributes]?: DsTab[K] } & { [K in keyof DsTab & keyof DsTabAttributes as `attr:${K}`]?: DsTabAttributes[K] } & { [K in keyof DsTab & keyof DsTabAttributes as `prop:${K}`]?: DsTab[K] };
        "ds-tab-panel": Omit<DsTabPanel, keyof DsTabPanelAttributes> & { [K in keyof DsTabPanel & keyof DsTabPanelAttributes]?: DsTabPanel[K] } & { [K in keyof DsTabPanel & keyof DsTabPanelAttributes as `attr:${K}`]?: DsTabPanelAttributes[K] } & { [K in keyof DsTabPanel & keyof DsTabPanelAttributes as `prop:${K}`]?: DsTabPanel[K] };
        "ds-table": Omit<DsTable, keyof DsTableAttributes> & { [K in keyof DsTable & keyof DsTableAttributes]?: DsTable[K] } & { [K in keyof DsTable & keyof DsTableAttributes as `attr:${K}`]?: DsTableAttributes[K] } & { [K in keyof DsTable & keyof DsTableAttributes as `prop:${K}`]?: DsTable[K] };
        "ds-tabs": Omit<DsTabs, keyof DsTabsAttributes> & { [K in keyof DsTabs & keyof DsTabsAttributes]?: DsTabs[K] } & { [K in keyof DsTabs & keyof DsTabsAttributes as `attr:${K}`]?: DsTabsAttributes[K] } & { [K in keyof DsTabs & keyof DsTabsAttributes as `prop:${K}`]?: DsTabs[K] };
        "ds-tag": Omit<DsTag, keyof DsTagAttributes> & { [K in keyof DsTag & keyof DsTagAttributes]?: DsTag[K] } & { [K in keyof DsTag & keyof DsTagAttributes as `attr:${K}`]?: DsTagAttributes[K] } & { [K in keyof DsTag & keyof DsTagAttributes as `prop:${K}`]?: DsTag[K] };
        "ds-timeline": DsTimeline;
        "ds-toast": Omit<DsToast, keyof DsToastAttributes> & { [K in keyof DsToast & keyof DsToastAttributes]?: DsToast[K] } & { [K in keyof DsToast & keyof DsToastAttributes as `attr:${K}`]?: DsToastAttributes[K] } & { [K in keyof DsToast & keyof DsToastAttributes as `prop:${K}`]?: DsToast[K] };
        "ds-toast-container": Omit<DsToastContainer, keyof DsToastContainerAttributes> & { [K in keyof DsToastContainer & keyof DsToastContainerAttributes]?: DsToastContainer[K] } & { [K in keyof DsToastContainer & keyof DsToastContainerAttributes as `attr:${K}`]?: DsToastContainerAttributes[K] } & { [K in keyof DsToastContainer & keyof DsToastContainerAttributes as `prop:${K}`]?: DsToastContainer[K] };
        "ds-toggle": Omit<DsToggle, keyof DsToggleAttributes> & { [K in keyof DsToggle & keyof DsToggleAttributes]?: DsToggle[K] } & { [K in keyof DsToggle & keyof DsToggleAttributes as `attr:${K}`]?: DsToggleAttributes[K] } & { [K in keyof DsToggle & keyof DsToggleAttributes as `prop:${K}`]?: DsToggle[K] };
        "ds-tooltip": Omit<DsTooltip, keyof DsTooltipAttributes> & { [K in keyof DsTooltip & keyof DsTooltipAttributes]?: DsTooltip[K] } & { [K in keyof DsTooltip & keyof DsTooltipAttributes as `attr:${K}`]?: DsTooltipAttributes[K] } & { [K in keyof DsTooltip & keyof DsTooltipAttributes as `prop:${K}`]?: DsTooltip[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-accordion": LocalJSX.IntrinsicElements["ds-accordion"] & JSXBase.HTMLAttributes<HTMLDsAccordionElement>;
            "ds-accordion-item": LocalJSX.IntrinsicElements["ds-accordion-item"] & JSXBase.HTMLAttributes<HTMLDsAccordionItemElement>;
            "ds-alert": LocalJSX.IntrinsicElements["ds-alert"] & JSXBase.HTMLAttributes<HTMLDsAlertElement>;
            "ds-avatar": LocalJSX.IntrinsicElements["ds-avatar"] & JSXBase.HTMLAttributes<HTMLDsAvatarElement>;
            "ds-badge": LocalJSX.IntrinsicElements["ds-badge"] & JSXBase.HTMLAttributes<HTMLDsBadgeElement>;
            "ds-breadcrumb": LocalJSX.IntrinsicElements["ds-breadcrumb"] & JSXBase.HTMLAttributes<HTMLDsBreadcrumbElement>;
            "ds-breadcrumb-item": LocalJSX.IntrinsicElements["ds-breadcrumb-item"] & JSXBase.HTMLAttributes<HTMLDsBreadcrumbItemElement>;
            "ds-button": LocalJSX.IntrinsicElements["ds-button"] & JSXBase.HTMLAttributes<HTMLDsButtonElement>;
            "ds-card": LocalJSX.IntrinsicElements["ds-card"] & JSXBase.HTMLAttributes<HTMLDsCardElement>;
            "ds-chart-bar": LocalJSX.IntrinsicElements["ds-chart-bar"] & JSXBase.HTMLAttributes<HTMLDsChartBarElement>;
            "ds-chart-donut": LocalJSX.IntrinsicElements["ds-chart-donut"] & JSXBase.HTMLAttributes<HTMLDsChartDonutElement>;
            "ds-chart-line": LocalJSX.IntrinsicElements["ds-chart-line"] & JSXBase.HTMLAttributes<HTMLDsChartLineElement>;
            "ds-checkbox": LocalJSX.IntrinsicElements["ds-checkbox"] & JSXBase.HTMLAttributes<HTMLDsCheckboxElement>;
            "ds-checkbox-group": LocalJSX.IntrinsicElements["ds-checkbox-group"] & JSXBase.HTMLAttributes<HTMLDsCheckboxGroupElement>;
            "ds-dropdown": LocalJSX.IntrinsicElements["ds-dropdown"] & JSXBase.HTMLAttributes<HTMLDsDropdownElement>;
            "ds-dropdown-item": LocalJSX.IntrinsicElements["ds-dropdown-item"] & JSXBase.HTMLAttributes<HTMLDsDropdownItemElement>;
            "ds-input": LocalJSX.IntrinsicElements["ds-input"] & JSXBase.HTMLAttributes<HTMLDsInputElement>;
            "ds-modal": LocalJSX.IntrinsicElements["ds-modal"] & JSXBase.HTMLAttributes<HTMLDsModalElement>;
            "ds-pagination": LocalJSX.IntrinsicElements["ds-pagination"] & JSXBase.HTMLAttributes<HTMLDsPaginationElement>;
            "ds-progress": LocalJSX.IntrinsicElements["ds-progress"] & JSXBase.HTMLAttributes<HTMLDsProgressElement>;
            "ds-radio": LocalJSX.IntrinsicElements["ds-radio"] & JSXBase.HTMLAttributes<HTMLDsRadioElement>;
            "ds-radio-group": LocalJSX.IntrinsicElements["ds-radio-group"] & JSXBase.HTMLAttributes<HTMLDsRadioGroupElement>;
            "ds-select": LocalJSX.IntrinsicElements["ds-select"] & JSXBase.HTMLAttributes<HTMLDsSelectElement>;
            "ds-skeleton": LocalJSX.IntrinsicElements["ds-skeleton"] & JSXBase.HTMLAttributes<HTMLDsSkeletonElement>;
            "ds-spinner": LocalJSX.IntrinsicElements["ds-spinner"] & JSXBase.HTMLAttributes<HTMLDsSpinnerElement>;
            "ds-stat-card": LocalJSX.IntrinsicElements["ds-stat-card"] & JSXBase.HTMLAttributes<HTMLDsStatCardElement>;
            "ds-stepper": LocalJSX.IntrinsicElements["ds-stepper"] & JSXBase.HTMLAttributes<HTMLDsStepperElement>;
            "ds-tab": LocalJSX.IntrinsicElements["ds-tab"] & JSXBase.HTMLAttributes<HTMLDsTabElement>;
            "ds-tab-panel": LocalJSX.IntrinsicElements["ds-tab-panel"] & JSXBase.HTMLAttributes<HTMLDsTabPanelElement>;
            "ds-table": LocalJSX.IntrinsicElements["ds-table"] & JSXBase.HTMLAttributes<HTMLDsTableElement>;
            "ds-tabs": LocalJSX.IntrinsicElements["ds-tabs"] & JSXBase.HTMLAttributes<HTMLDsTabsElement>;
            "ds-tag": LocalJSX.IntrinsicElements["ds-tag"] & JSXBase.HTMLAttributes<HTMLDsTagElement>;
            "ds-timeline": LocalJSX.IntrinsicElements["ds-timeline"] & JSXBase.HTMLAttributes<HTMLDsTimelineElement>;
            "ds-toast": LocalJSX.IntrinsicElements["ds-toast"] & JSXBase.HTMLAttributes<HTMLDsToastElement>;
            "ds-toast-container": LocalJSX.IntrinsicElements["ds-toast-container"] & JSXBase.HTMLAttributes<HTMLDsToastContainerElement>;
            "ds-toggle": LocalJSX.IntrinsicElements["ds-toggle"] & JSXBase.HTMLAttributes<HTMLDsToggleElement>;
            "ds-tooltip": LocalJSX.IntrinsicElements["ds-tooltip"] & JSXBase.HTMLAttributes<HTMLDsTooltipElement>;
        }
    }
}
