'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { type DsButtonCustomEvent, type DsTableCustomEvent, type SortEvent } from "@ds/core";
import { DsAccordionItem as DsAccordionItemElement, defineCustomElement as defineDsAccordionItem } from "@ds/core/dist/components/ds-accordion-item.js";
import { DsAccordion as DsAccordionElement, defineCustomElement as defineDsAccordion } from "@ds/core/dist/components/ds-accordion.js";
import { DsAlert as DsAlertElement, defineCustomElement as defineDsAlert } from "@ds/core/dist/components/ds-alert.js";
import { DsAvatar as DsAvatarElement, defineCustomElement as defineDsAvatar } from "@ds/core/dist/components/ds-avatar.js";
import { DsBadge as DsBadgeElement, defineCustomElement as defineDsBadge } from "@ds/core/dist/components/ds-badge.js";
import { DsBreadcrumbItem as DsBreadcrumbItemElement, defineCustomElement as defineDsBreadcrumbItem } from "@ds/core/dist/components/ds-breadcrumb-item.js";
import { DsBreadcrumb as DsBreadcrumbElement, defineCustomElement as defineDsBreadcrumb } from "@ds/core/dist/components/ds-breadcrumb.js";
import { DsButton as DsButtonElement, defineCustomElement as defineDsButton } from "@ds/core/dist/components/ds-button.js";
import { DsCard as DsCardElement, defineCustomElement as defineDsCard } from "@ds/core/dist/components/ds-card.js";
import { DsChartBar as DsChartBarElement, defineCustomElement as defineDsChartBar } from "@ds/core/dist/components/ds-chart-bar.js";
import { DsChartDonut as DsChartDonutElement, defineCustomElement as defineDsChartDonut } from "@ds/core/dist/components/ds-chart-donut.js";
import { DsChartLine as DsChartLineElement, defineCustomElement as defineDsChartLine } from "@ds/core/dist/components/ds-chart-line.js";
import { DsCheckboxGroup as DsCheckboxGroupElement, defineCustomElement as defineDsCheckboxGroup } from "@ds/core/dist/components/ds-checkbox-group.js";
import { DsCheckbox as DsCheckboxElement, defineCustomElement as defineDsCheckbox } from "@ds/core/dist/components/ds-checkbox.js";
import { DsDropdownItem as DsDropdownItemElement, defineCustomElement as defineDsDropdownItem } from "@ds/core/dist/components/ds-dropdown-item.js";
import { DsDropdown as DsDropdownElement, defineCustomElement as defineDsDropdown } from "@ds/core/dist/components/ds-dropdown.js";
import { DsInput as DsInputElement, defineCustomElement as defineDsInput } from "@ds/core/dist/components/ds-input.js";
import { DsModal as DsModalElement, defineCustomElement as defineDsModal } from "@ds/core/dist/components/ds-modal.js";
import { DsPagination as DsPaginationElement, defineCustomElement as defineDsPagination } from "@ds/core/dist/components/ds-pagination.js";
import { DsProgress as DsProgressElement, defineCustomElement as defineDsProgress } from "@ds/core/dist/components/ds-progress.js";
import { DsRadioGroup as DsRadioGroupElement, defineCustomElement as defineDsRadioGroup } from "@ds/core/dist/components/ds-radio-group.js";
import { DsRadio as DsRadioElement, defineCustomElement as defineDsRadio } from "@ds/core/dist/components/ds-radio.js";
import { DsSelect as DsSelectElement, defineCustomElement as defineDsSelect } from "@ds/core/dist/components/ds-select.js";
import { DsSkeleton as DsSkeletonElement, defineCustomElement as defineDsSkeleton } from "@ds/core/dist/components/ds-skeleton.js";
import { DsSpinner as DsSpinnerElement, defineCustomElement as defineDsSpinner } from "@ds/core/dist/components/ds-spinner.js";
import { DsStatCard as DsStatCardElement, defineCustomElement as defineDsStatCard } from "@ds/core/dist/components/ds-stat-card.js";
import { DsStepper as DsStepperElement, defineCustomElement as defineDsStepper } from "@ds/core/dist/components/ds-stepper.js";
import { DsTabPanel as DsTabPanelElement, defineCustomElement as defineDsTabPanel } from "@ds/core/dist/components/ds-tab-panel.js";
import { DsTab as DsTabElement, defineCustomElement as defineDsTab } from "@ds/core/dist/components/ds-tab.js";
import { DsTable as DsTableElement, defineCustomElement as defineDsTable } from "@ds/core/dist/components/ds-table.js";
import { DsTabs as DsTabsElement, defineCustomElement as defineDsTabs } from "@ds/core/dist/components/ds-tabs.js";
import { DsTag as DsTagElement, defineCustomElement as defineDsTag } from "@ds/core/dist/components/ds-tag.js";
import { DsTimeline as DsTimelineElement, defineCustomElement as defineDsTimeline } from "@ds/core/dist/components/ds-timeline.js";
import { DsToastContainer as DsToastContainerElement, defineCustomElement as defineDsToastContainer } from "@ds/core/dist/components/ds-toast-container.js";
import { DsToast as DsToastElement, defineCustomElement as defineDsToast } from "@ds/core/dist/components/ds-toast.js";
import { DsToggle as DsToggleElement, defineCustomElement as defineDsToggle } from "@ds/core/dist/components/ds-toggle.js";
import { DsTooltip as DsTooltipElement, defineCustomElement as defineDsTooltip } from "@ds/core/dist/components/ds-tooltip.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type DsAccordionEvents = NonNullable<unknown>;

export const DsAccordion: StencilReactComponent<DsAccordionElement, DsAccordionEvents> = /*@__PURE__*/ createComponent<DsAccordionElement, DsAccordionEvents>({
    tagName: 'ds-accordion',
    elementClass: DsAccordionElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsAccordionEvents,
    defineCustomElement: defineDsAccordion
});

type DsAccordionItemEvents = { onDsToggle: EventName<CustomEvent<{ value: string; open: boolean }>> };

export const DsAccordionItem: StencilReactComponent<DsAccordionItemElement, DsAccordionItemEvents> = /*@__PURE__*/ createComponent<DsAccordionItemElement, DsAccordionItemEvents>({
    tagName: 'ds-accordion-item',
    elementClass: DsAccordionItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onDsToggle: 'dsToggle' } as DsAccordionItemEvents,
    defineCustomElement: defineDsAccordionItem
});

type DsAlertEvents = { onDsDismiss: EventName<CustomEvent<void>> };

export const DsAlert: StencilReactComponent<DsAlertElement, DsAlertEvents> = /*@__PURE__*/ createComponent<DsAlertElement, DsAlertEvents>({
    tagName: 'ds-alert',
    elementClass: DsAlertElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onDsDismiss: 'dsDismiss' } as DsAlertEvents,
    defineCustomElement: defineDsAlert
});

type DsAvatarEvents = NonNullable<unknown>;

export const DsAvatar: StencilReactComponent<DsAvatarElement, DsAvatarEvents> = /*@__PURE__*/ createComponent<DsAvatarElement, DsAvatarEvents>({
    tagName: 'ds-avatar',
    elementClass: DsAvatarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsAvatarEvents,
    defineCustomElement: defineDsAvatar
});

type DsBadgeEvents = NonNullable<unknown>;

export const DsBadge: StencilReactComponent<DsBadgeElement, DsBadgeEvents> = /*@__PURE__*/ createComponent<DsBadgeElement, DsBadgeEvents>({
    tagName: 'ds-badge',
    elementClass: DsBadgeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsBadgeEvents,
    defineCustomElement: defineDsBadge
});

type DsBreadcrumbEvents = NonNullable<unknown>;

export const DsBreadcrumb: StencilReactComponent<DsBreadcrumbElement, DsBreadcrumbEvents> = /*@__PURE__*/ createComponent<DsBreadcrumbElement, DsBreadcrumbEvents>({
    tagName: 'ds-breadcrumb',
    elementClass: DsBreadcrumbElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsBreadcrumbEvents,
    defineCustomElement: defineDsBreadcrumb
});

type DsBreadcrumbItemEvents = NonNullable<unknown>;

export const DsBreadcrumbItem: StencilReactComponent<DsBreadcrumbItemElement, DsBreadcrumbItemEvents> = /*@__PURE__*/ createComponent<DsBreadcrumbItemElement, DsBreadcrumbItemEvents>({
    tagName: 'ds-breadcrumb-item',
    elementClass: DsBreadcrumbItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsBreadcrumbItemEvents,
    defineCustomElement: defineDsBreadcrumbItem
});

type DsButtonEvents = { onDsClick: EventName<DsButtonCustomEvent<MouseEvent>> };

export const DsButton: StencilReactComponent<DsButtonElement, DsButtonEvents> = /*@__PURE__*/ createComponent<DsButtonElement, DsButtonEvents>({
    tagName: 'ds-button',
    elementClass: DsButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onDsClick: 'dsClick' } as DsButtonEvents,
    defineCustomElement: defineDsButton
});

type DsCardEvents = NonNullable<unknown>;

export const DsCard: StencilReactComponent<DsCardElement, DsCardEvents> = /*@__PURE__*/ createComponent<DsCardElement, DsCardEvents>({
    tagName: 'ds-card',
    elementClass: DsCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsCardEvents,
    defineCustomElement: defineDsCard
});

type DsChartBarEvents = NonNullable<unknown>;

export const DsChartBar: StencilReactComponent<DsChartBarElement, DsChartBarEvents> = /*@__PURE__*/ createComponent<DsChartBarElement, DsChartBarEvents>({
    tagName: 'ds-chart-bar',
    elementClass: DsChartBarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsChartBarEvents,
    defineCustomElement: defineDsChartBar
});

type DsChartDonutEvents = NonNullable<unknown>;

export const DsChartDonut: StencilReactComponent<DsChartDonutElement, DsChartDonutEvents> = /*@__PURE__*/ createComponent<DsChartDonutElement, DsChartDonutEvents>({
    tagName: 'ds-chart-donut',
    elementClass: DsChartDonutElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsChartDonutEvents,
    defineCustomElement: defineDsChartDonut
});

type DsChartLineEvents = NonNullable<unknown>;

export const DsChartLine: StencilReactComponent<DsChartLineElement, DsChartLineEvents> = /*@__PURE__*/ createComponent<DsChartLineElement, DsChartLineEvents>({
    tagName: 'ds-chart-line',
    elementClass: DsChartLineElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsChartLineEvents,
    defineCustomElement: defineDsChartLine
});

type DsCheckboxEvents = { onDsChange: EventName<CustomEvent<boolean>> };

export const DsCheckbox: StencilReactComponent<DsCheckboxElement, DsCheckboxEvents> = /*@__PURE__*/ createComponent<DsCheckboxElement, DsCheckboxEvents>({
    tagName: 'ds-checkbox',
    elementClass: DsCheckboxElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onDsChange: 'dsChange' } as DsCheckboxEvents,
    defineCustomElement: defineDsCheckbox
});

type DsCheckboxGroupEvents = { onDsGroupChange: EventName<CustomEvent<void>> };

export const DsCheckboxGroup: StencilReactComponent<DsCheckboxGroupElement, DsCheckboxGroupEvents> = /*@__PURE__*/ createComponent<DsCheckboxGroupElement, DsCheckboxGroupEvents>({
    tagName: 'ds-checkbox-group',
    elementClass: DsCheckboxGroupElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onDsGroupChange: 'dsGroupChange' } as DsCheckboxGroupEvents,
    defineCustomElement: defineDsCheckboxGroup
});

type DsDropdownEvents = {
    onDsOpen: EventName<CustomEvent<void>>,
    onDsClose: EventName<CustomEvent<void>>
};

export const DsDropdown: StencilReactComponent<DsDropdownElement, DsDropdownEvents> = /*@__PURE__*/ createComponent<DsDropdownElement, DsDropdownEvents>({
    tagName: 'ds-dropdown',
    elementClass: DsDropdownElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onDsOpen: 'dsOpen',
        onDsClose: 'dsClose'
    } as DsDropdownEvents,
    defineCustomElement: defineDsDropdown
});

type DsDropdownItemEvents = { onDsSelect: EventName<CustomEvent<void>> };

export const DsDropdownItem: StencilReactComponent<DsDropdownItemElement, DsDropdownItemEvents> = /*@__PURE__*/ createComponent<DsDropdownItemElement, DsDropdownItemEvents>({
    tagName: 'ds-dropdown-item',
    elementClass: DsDropdownItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onDsSelect: 'dsSelect' } as DsDropdownItemEvents,
    defineCustomElement: defineDsDropdownItem
});

type DsInputEvents = {
    onDsInput: EventName<CustomEvent<string>>,
    onDsChange: EventName<CustomEvent<string>>,
    onDsFocus: EventName<CustomEvent<void>>,
    onDsBlur: EventName<CustomEvent<void>>
};

export const DsInput: StencilReactComponent<DsInputElement, DsInputEvents> = /*@__PURE__*/ createComponent<DsInputElement, DsInputEvents>({
    tagName: 'ds-input',
    elementClass: DsInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onDsInput: 'dsInput',
        onDsChange: 'dsChange',
        onDsFocus: 'dsFocus',
        onDsBlur: 'dsBlur'
    } as DsInputEvents,
    defineCustomElement: defineDsInput
});

type DsModalEvents = {
    onDsOpen: EventName<CustomEvent<void>>,
    onDsClose: EventName<CustomEvent<void>>,
    onDsAfterOpen: EventName<CustomEvent<void>>,
    onDsAfterClose: EventName<CustomEvent<void>>
};

export const DsModal: StencilReactComponent<DsModalElement, DsModalEvents> = /*@__PURE__*/ createComponent<DsModalElement, DsModalEvents>({
    tagName: 'ds-modal',
    elementClass: DsModalElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onDsOpen: 'dsOpen',
        onDsClose: 'dsClose',
        onDsAfterOpen: 'dsAfterOpen',
        onDsAfterClose: 'dsAfterClose'
    } as DsModalEvents,
    defineCustomElement: defineDsModal
});

type DsPaginationEvents = { onDsPageChange: EventName<CustomEvent<number>> };

export const DsPagination: StencilReactComponent<DsPaginationElement, DsPaginationEvents> = /*@__PURE__*/ createComponent<DsPaginationElement, DsPaginationEvents>({
    tagName: 'ds-pagination',
    elementClass: DsPaginationElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onDsPageChange: 'dsPageChange' } as DsPaginationEvents,
    defineCustomElement: defineDsPagination
});

type DsProgressEvents = NonNullable<unknown>;

export const DsProgress: StencilReactComponent<DsProgressElement, DsProgressEvents> = /*@__PURE__*/ createComponent<DsProgressElement, DsProgressEvents>({
    tagName: 'ds-progress',
    elementClass: DsProgressElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsProgressEvents,
    defineCustomElement: defineDsProgress
});

type DsRadioEvents = { onDsChange: EventName<CustomEvent<string>> };

export const DsRadio: StencilReactComponent<DsRadioElement, DsRadioEvents> = /*@__PURE__*/ createComponent<DsRadioElement, DsRadioEvents>({
    tagName: 'ds-radio',
    elementClass: DsRadioElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onDsChange: 'dsChange' } as DsRadioEvents,
    defineCustomElement: defineDsRadio
});

type DsRadioGroupEvents = { onDsChange: EventName<CustomEvent<string>> };

export const DsRadioGroup: StencilReactComponent<DsRadioGroupElement, DsRadioGroupEvents> = /*@__PURE__*/ createComponent<DsRadioGroupElement, DsRadioGroupEvents>({
    tagName: 'ds-radio-group',
    elementClass: DsRadioGroupElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onDsChange: 'dsChange' } as DsRadioGroupEvents,
    defineCustomElement: defineDsRadioGroup
});

type DsSelectEvents = {
    onDsChange: EventName<CustomEvent<string>>,
    onDsSearch: EventName<CustomEvent<string>>
};

export const DsSelect: StencilReactComponent<DsSelectElement, DsSelectEvents> = /*@__PURE__*/ createComponent<DsSelectElement, DsSelectEvents>({
    tagName: 'ds-select',
    elementClass: DsSelectElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onDsChange: 'dsChange',
        onDsSearch: 'dsSearch'
    } as DsSelectEvents,
    defineCustomElement: defineDsSelect
});

type DsSkeletonEvents = NonNullable<unknown>;

export const DsSkeleton: StencilReactComponent<DsSkeletonElement, DsSkeletonEvents> = /*@__PURE__*/ createComponent<DsSkeletonElement, DsSkeletonEvents>({
    tagName: 'ds-skeleton',
    elementClass: DsSkeletonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsSkeletonEvents,
    defineCustomElement: defineDsSkeleton
});

type DsSpinnerEvents = NonNullable<unknown>;

export const DsSpinner: StencilReactComponent<DsSpinnerElement, DsSpinnerEvents> = /*@__PURE__*/ createComponent<DsSpinnerElement, DsSpinnerEvents>({
    tagName: 'ds-spinner',
    elementClass: DsSpinnerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsSpinnerEvents,
    defineCustomElement: defineDsSpinner
});

type DsStatCardEvents = NonNullable<unknown>;

export const DsStatCard: StencilReactComponent<DsStatCardElement, DsStatCardEvents> = /*@__PURE__*/ createComponent<DsStatCardElement, DsStatCardEvents>({
    tagName: 'ds-stat-card',
    elementClass: DsStatCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsStatCardEvents,
    defineCustomElement: defineDsStatCard
});

type DsStepperEvents = NonNullable<unknown>;

export const DsStepper: StencilReactComponent<DsStepperElement, DsStepperEvents> = /*@__PURE__*/ createComponent<DsStepperElement, DsStepperEvents>({
    tagName: 'ds-stepper',
    elementClass: DsStepperElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsStepperEvents,
    defineCustomElement: defineDsStepper
});

type DsTabEvents = NonNullable<unknown>;

export const DsTab: StencilReactComponent<DsTabElement, DsTabEvents> = /*@__PURE__*/ createComponent<DsTabElement, DsTabEvents>({
    tagName: 'ds-tab',
    elementClass: DsTabElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsTabEvents,
    defineCustomElement: defineDsTab
});

type DsTabPanelEvents = NonNullable<unknown>;

export const DsTabPanel: StencilReactComponent<DsTabPanelElement, DsTabPanelEvents> = /*@__PURE__*/ createComponent<DsTabPanelElement, DsTabPanelEvents>({
    tagName: 'ds-tab-panel',
    elementClass: DsTabPanelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsTabPanelEvents,
    defineCustomElement: defineDsTabPanel
});

type DsTableEvents = {
    onDsSort: EventName<DsTableCustomEvent<SortEvent>>,
    onDsRowClick: EventName<DsTableCustomEvent<Record<string, unknown>>>
};

export const DsTable: StencilReactComponent<DsTableElement, DsTableEvents> = /*@__PURE__*/ createComponent<DsTableElement, DsTableEvents>({
    tagName: 'ds-table',
    elementClass: DsTableElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onDsSort: 'dsSort',
        onDsRowClick: 'dsRowClick'
    } as DsTableEvents,
    defineCustomElement: defineDsTable
});

type DsTabsEvents = { onDsChange: EventName<CustomEvent<string>> };

export const DsTabs: StencilReactComponent<DsTabsElement, DsTabsEvents> = /*@__PURE__*/ createComponent<DsTabsElement, DsTabsEvents>({
    tagName: 'ds-tabs',
    elementClass: DsTabsElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onDsChange: 'dsChange' } as DsTabsEvents,
    defineCustomElement: defineDsTabs
});

type DsTagEvents = { onDsRemove: EventName<CustomEvent<void>> };

export const DsTag: StencilReactComponent<DsTagElement, DsTagEvents> = /*@__PURE__*/ createComponent<DsTagElement, DsTagEvents>({
    tagName: 'ds-tag',
    elementClass: DsTagElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onDsRemove: 'dsRemove' } as DsTagEvents,
    defineCustomElement: defineDsTag
});

type DsTimelineEvents = NonNullable<unknown>;

export const DsTimeline: StencilReactComponent<DsTimelineElement, DsTimelineEvents> = /*@__PURE__*/ createComponent<DsTimelineElement, DsTimelineEvents>({
    tagName: 'ds-timeline',
    elementClass: DsTimelineElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsTimelineEvents,
    defineCustomElement: defineDsTimeline
});

type DsToastEvents = { onDsDismiss: EventName<CustomEvent<void>> };

export const DsToast: StencilReactComponent<DsToastElement, DsToastEvents> = /*@__PURE__*/ createComponent<DsToastElement, DsToastEvents>({
    tagName: 'ds-toast',
    elementClass: DsToastElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onDsDismiss: 'dsDismiss' } as DsToastEvents,
    defineCustomElement: defineDsToast
});

type DsToastContainerEvents = NonNullable<unknown>;

export const DsToastContainer: StencilReactComponent<DsToastContainerElement, DsToastContainerEvents> = /*@__PURE__*/ createComponent<DsToastContainerElement, DsToastContainerEvents>({
    tagName: 'ds-toast-container',
    elementClass: DsToastContainerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsToastContainerEvents,
    defineCustomElement: defineDsToastContainer
});

type DsToggleEvents = { onDsChange: EventName<CustomEvent<boolean>> };

export const DsToggle: StencilReactComponent<DsToggleElement, DsToggleEvents> = /*@__PURE__*/ createComponent<DsToggleElement, DsToggleEvents>({
    tagName: 'ds-toggle',
    elementClass: DsToggleElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onDsChange: 'dsChange' } as DsToggleEvents,
    defineCustomElement: defineDsToggle
});

type DsTooltipEvents = NonNullable<unknown>;

export const DsTooltip: StencilReactComponent<DsTooltipElement, DsTooltipEvents> = /*@__PURE__*/ createComponent<DsTooltipElement, DsTooltipEvents>({
    tagName: 'ds-tooltip',
    elementClass: DsTooltipElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as DsTooltipEvents,
    defineCustomElement: defineDsTooltip
});
