
import * as d from './components';

export const DIRECTIVES = [
  d.DsAccordion,
  d.DsAccordionItem,
  d.DsAlert,
  d.DsAvatar,
  d.DsBadge,
  d.DsBreadcrumb,
  d.DsBreadcrumbItem,
  d.DsButton,
  d.DsCard,
  d.DsChartBar,
  d.DsChartDonut,
  d.DsChartLine,
  d.DsCheckbox,
  d.DsCheckboxGroup,
  d.DsDropdown,
  d.DsDropdownItem,
  d.DsInput,
  d.DsModal,
  d.DsPagination,
  d.DsProgress,
  d.DsRadio,
  d.DsRadioGroup,
  d.DsSelect,
  d.DsSkeleton,
  d.DsSpinner,
  d.DsStatCard,
  d.DsStepper,
  d.DsTab,
  d.DsTabPanel,
  d.DsTable,
  d.DsTabs,
  d.DsTag,
  d.DsTimeline,
  d.DsToast,
  d.DsToastContainer,
  d.DsToggle,
  d.DsTooltip
];
